const slugRegex = /^[a-z0-9]([a-z0-9-]{1,61}[a-z0-9])?$/;

const reservedSlugs = new Set([
  // tech brands
  "google",
  "gmail",
  "apple",
  "iphone",
  "macbook",
  "microsoft",
  "windows",
  "amazon",
  "netflix",
  "tesla",
  "instagram",
  "facebook",
  "meta",
  "whatsapp",
  "youtube",
  "tiktok",
  "twitter",
  "x",
  "paypal",
  "spotify",
  "adobe",
  "samsung",
  "huawei",
  "intel",
  "nvidia",
  "oracle",
  "zoom",
  "slack",
  "github",
  // gov / public sector
  "government",
  "ministry",
  "tax",
  "police",
  "court",
  "senate",
  "parliament",
  "army",
  "gov",
  "kremlin",
  "who",
  "un",
  "nasa",
  "eu",
  "fbi",
  "cia",
  "justice",
  "prosecutor",
  "embassy",
  "customs",
  // individuals
  "elonmusk",
  "jeffbezos",
  "billgates",
  "sundarpichai",
  "markzuckerberg",
  "kimkardashian",
  "dojacat",
  "taylorswift",
  "trump",
  "putin",
  "navalny",
  "biden",
  "musk",
  "zuckerberg",
  "bezos",
  "gates",
  // generic risky terms
  "bank",
  "support",
  "service",
  "payment",
  "secure",
  "security",
  "verify",
  "update",
  "official",
  "admin",
  "moderator",
  "owner",
  "ceo",
  "founder",
  "legal",
  "billing",
  "sync",
  "api",
  "notepub",
  "np",
  "np-official",
  "notepub-official",
]);

export function normalizeSlug(input: string) {
  const slug = input.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-{2,}/g, "-").replace(/^-+|-+$/g, "");
  if (!slugRegex.test(slug)) return "";
  return slug;
}

export function isReservedSlug(slug: string) {
  const normalized = slug.toLowerCase();
  return reservedSlugs.has(normalized);
}
